// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef DRONE_CONTROLLER_REG_H
#define DRONE_CONTROLLER_REG_H

#ifdef __cplusplus
extern "C" {
#endif
#include <stdint.h>

// reg - pwm_channel_t::CONF
#define PWM_CHANNEL_T__CONF__MODE_bm 0x3
#define PWM_CHANNEL_T__CONF__MODE_bp 0
#define PWM_CHANNEL_T__CONF__MODE_bw 2
#define PWM_CHANNEL_T__CONF__MODE_reset 0x0
#define PWM_CHANNEL_T__CONF__CLK_DIV_bm 0xc
#define PWM_CHANNEL_T__CONF__CLK_DIV_bp 2
#define PWM_CHANNEL_T__CONF__CLK_DIV_bw 2
#define PWM_CHANNEL_T__CONF__CLK_DIV_reset 0x0

// reg - pwm_channel_t::COUNT_TOP
#define PWM_CHANNEL_T__COUNT_TOP__DATA_bm 0xffffffff
#define PWM_CHANNEL_T__COUNT_TOP__DATA_bp 0
#define PWM_CHANNEL_T__COUNT_TOP__DATA_bw 32
#define PWM_CHANNEL_T__COUNT_TOP__DATA_reset 0x0

// reg - pwm_channel_t::COUNT_COMPARE
#define PWM_CHANNEL_T__COUNT_COMPARE__DATA_bm 0xffffffff
#define PWM_CHANNEL_T__COUNT_COMPARE__DATA_bp 0
#define PWM_CHANNEL_T__COUNT_COMPARE__DATA_bw 32
#define PWM_CHANNEL_T__COUNT_COMPARE__DATA_reset 0x0

// regfile - pwm_channel_t
typedef struct __attribute__ ((__packed__)) {
    uint32_t CONF;
    uint32_t COUNT_TOP;
    uint32_t COUNT_COMPARE;
} pwm_channel_t_t;

// reg - controller_t::CMD
#define CONTROLLER_T__CMD__RUN_CALC_bm 0x1
#define CONTROLLER_T__CMD__RUN_CALC_bp 0
#define CONTROLLER_T__CMD__RUN_CALC_bw 1
#define CONTROLLER_T__CMD__RUN_CALC_reset 0x0
#define CONTROLLER_T__CMD__UPDATE_CONTROLLER_bm 0x2
#define CONTROLLER_T__CMD__UPDATE_CONTROLLER_bp 1
#define CONTROLLER_T__CMD__UPDATE_CONTROLLER_bw 1
#define CONTROLLER_T__CMD__UPDATE_CONTROLLER_reset 0x0
#define CONTROLLER_T__CMD__UPDATE_CONTROLLER_REFERENCE_bm 0x4
#define CONTROLLER_T__CMD__UPDATE_CONTROLLER_REFERENCE_bp 2
#define CONTROLLER_T__CMD__UPDATE_CONTROLLER_REFERENCE_bw 1
#define CONTROLLER_T__CMD__UPDATE_CONTROLLER_REFERENCE_reset 0x0
#define CONTROLLER_T__CMD__UPDATE_CONTROLLER_STATE_bm 0x8
#define CONTROLLER_T__CMD__UPDATE_CONTROLLER_STATE_bp 3
#define CONTROLLER_T__CMD__UPDATE_CONTROLLER_STATE_bw 1
#define CONTROLLER_T__CMD__UPDATE_CONTROLLER_STATE_reset 0x0

// reg - controller_t::K_MATRIX
#define CONTROLLER_T__K_MATRIX__POINTER_bm 0xffffffff
#define CONTROLLER_T__K_MATRIX__POINTER_bp 0
#define CONTROLLER_T__K_MATRIX__POINTER_bw 32
#define CONTROLLER_T__K_MATRIX__POINTER_reset 0x0

// reg - controller_t::X_REF_VEC
#define CONTROLLER_T__X_REF_VEC__POINTER_bm 0xffffffff
#define CONTROLLER_T__X_REF_VEC__POINTER_bp 0
#define CONTROLLER_T__X_REF_VEC__POINTER_bw 32
#define CONTROLLER_T__X_REF_VEC__POINTER_reset 0x0

// reg - controller_t::X_IN_VEC
#define CONTROLLER_T__X_IN_VEC__POINTER_bm 0xffffffff
#define CONTROLLER_T__X_IN_VEC__POINTER_bp 0
#define CONTROLLER_T__X_IN_VEC__POINTER_bw 32
#define CONTROLLER_T__X_IN_VEC__POINTER_reset 0x0

// reg - controller_t::U0_VEC
#define CONTROLLER_T__U0_VEC__POINTER_bm 0xffffffff
#define CONTROLLER_T__U0_VEC__POINTER_bp 0
#define CONTROLLER_T__U0_VEC__POINTER_bw 32
#define CONTROLLER_T__U0_VEC__POINTER_reset 0x0

// reg - controller_t::U_OUT_VEC
#define CONTROLLER_T__U_OUT_VEC__POINTER_bm 0xffffffff
#define CONTROLLER_T__U_OUT_VEC__POINTER_bp 0
#define CONTROLLER_T__U_OUT_VEC__POINTER_bw 32
#define CONTROLLER_T__U_OUT_VEC__POINTER_reset 0x0

// regfile - controller_t
typedef struct __attribute__ ((__packed__)) {
    uint32_t CMD;
    uint32_t K_MATRIX;
    uint32_t X_REF_VEC;
    uint32_t X_IN_VEC;
    uint32_t U0_VEC;
    uint32_t U_OUT_VEC;
} controller_t_t;

// addrmap - drone_controller_reg
typedef struct __attribute__ ((__packed__)) {
    pwm_channel_t_t pwm_ch[4];
    uint8_t RESERVED_30_3f[0x10];
    controller_t_t controller;
} drone_controller_reg_t;



#ifdef __cplusplus
}
#endif

#endif /* DRONE_CONTROLLER_REG_H */
