// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module drone_controller_reg #(
        parameter ID_WIDTH = 1
    ) (
        input wire clk,
        input wire rst,

        input wire s_obi_req,
        output logic s_obi_gnt,
        input wire [6:0] s_obi_addr,
        input wire s_obi_we,
        input wire [3:0] s_obi_be,
        input wire [31:0] s_obi_wdata,
        input wire [ID_WIDTH-1:0] s_obi_aid,
        output logic s_obi_rvalid,
        input wire s_obi_rready,
        output logic [31:0] s_obi_rdata,
        output logic s_obi_err,
        output logic [ID_WIDTH-1:0] s_obi_rid,

        output drone_controller_reg_pkg::drone_controller_reg__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [6:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    // State & holding regs
    logic is_active; // A request is being served (not yet fully responded)
    logic gnt_q; // one-cycle grant for A-channel
    logic rsp_pending; // response ready but not yet accepted by manager
    logic [31:0] rsp_rdata_q;
    logic rsp_err_q;
    logic [$bits(s_obi_rid)-1:0] rid_q;

    // Latch AID on accept to echo back the response
    always_ff @(posedge clk) begin
        if (rst) begin
            is_active <= 1'b0;
            gnt_q <= 1'b0;
            rsp_pending <= 1'b0;
            rsp_rdata_q <= '0;
            rsp_err_q <= 1'b0;
            rid_q <= '0;

            cpuif_req <= '0;
            cpuif_req_is_wr <= '0;
            cpuif_addr <= '0;
            cpuif_wr_data <= '0;
            cpuif_wr_biten <= '0;
        end else begin
            // defaults
            cpuif_req <= 1'b0;
            gnt_q <= s_obi_req & ~is_active;

            // Accept new request when idle
            if (~is_active) begin
                if (s_obi_req) begin
                    is_active <= 1'b1;
                    cpuif_req <= 1'b1;
                    cpuif_req_is_wr <= s_obi_we;
                    cpuif_addr <= {s_obi_addr[6:2], 2'b0};
                    cpuif_wr_data <= s_obi_wdata;
                    rid_q <= s_obi_aid;
                    for (int i = 0; i < 4; i++) begin
                        cpuif_wr_biten[i*8 +: 8] <= {8{ s_obi_be[i] }};
                    end
                end
            end

            // Capture response
            if (is_active && (cpuif_rd_ack || cpuif_wr_ack)) begin
                rsp_pending <= 1'b1;
                rsp_rdata_q <= cpuif_rd_data;
                rsp_err_q <= cpuif_rd_err | cpuif_wr_err;
                // NOTE: Keep 'is_active' asserted until the external R handshake completes
            end

            // Complete external R-channel handshake only if manager ready
            if (rsp_pending && s_obi_rvalid && s_obi_rready) begin
                rsp_pending <= 1'b0;
                is_active <= 1'b0; // free to accept the next request
            end
        end
    end

    // R-channel outputs (held stable while rsp_pending=1)
    assign s_obi_rvalid = rsp_pending;
    assign s_obi_rdata = rsp_rdata_q;
    assign s_obi_err = rsp_err_q;
    assign s_obi_rid = rid_q;

    // A-channel grant (registered one-cycle pulse when we accept a request)
    assign s_obi_gnt = gnt_q;

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            logic CONF;
            logic COUNT_TOP;
            logic COUNT_COMPARE;
        } pwm_ch[4];
        struct {
            logic CMD;
            logic K_MATRIX;
            logic X_REF_VEC;
            logic X_IN_VEC;
            logic U0_VEC;
            logic U_OUT_VEC;
        } controller;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_err;
    logic [6:0] decoded_addr;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        automatic logic is_valid_addr;
        automatic logic is_valid_rw;
        is_valid_addr = '1; // No valid address check
        is_valid_rw = '1; // No valid RW check
        for(int i0=0; i0<4; i0++) begin
            decoded_reg_strb.pwm_ch[i0].CONF = cpuif_req_masked & (cpuif_addr == 7'h0 + (7)'(i0) * 7'hc);
            decoded_reg_strb.pwm_ch[i0].COUNT_TOP = cpuif_req_masked & (cpuif_addr == 7'h4 + (7)'(i0) * 7'hc);
            decoded_reg_strb.pwm_ch[i0].COUNT_COMPARE = cpuif_req_masked & (cpuif_addr == 7'h8 + (7)'(i0) * 7'hc);
        end
        decoded_reg_strb.controller.CMD = cpuif_req_masked & (cpuif_addr == 7'h40) & cpuif_req_is_wr;
        decoded_reg_strb.controller.K_MATRIX = cpuif_req_masked & (cpuif_addr == 7'h44) & cpuif_req_is_wr;
        decoded_reg_strb.controller.X_REF_VEC = cpuif_req_masked & (cpuif_addr == 7'h48) & cpuif_req_is_wr;
        decoded_reg_strb.controller.X_IN_VEC = cpuif_req_masked & (cpuif_addr == 7'h4c) & cpuif_req_is_wr;
        decoded_reg_strb.controller.U0_VEC = cpuif_req_masked & (cpuif_addr == 7'h50) & cpuif_req_is_wr;
        decoded_reg_strb.controller.U_OUT_VEC = cpuif_req_masked & (cpuif_addr == 7'h54) & cpuif_req_is_wr;
        decoded_err = '0;
    end

    // Pass down signals to next stage
    assign decoded_addr = cpuif_addr;
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                struct {
                    logic [1:0] next;
                    logic load_next;
                } MODE;
                struct {
                    logic [1:0] next;
                    logic load_next;
                } CLK_DIV;
            } CONF;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } DATA;
            } COUNT_TOP;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } DATA;
            } COUNT_COMPARE;
        } pwm_ch[4];
        struct {
            struct {
                struct {
                    logic next;
                    logic load_next;
                } RUN_CALC;
                struct {
                    logic next;
                    logic load_next;
                } UPDATE_CONTROLLER;
                struct {
                    logic next;
                    logic load_next;
                } UPDATE_CONTROLLER_REFERENCE;
                struct {
                    logic next;
                    logic load_next;
                } UPDATE_CONTROLLER_STATE;
            } CMD;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } POINTER;
            } K_MATRIX;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } POINTER;
            } X_REF_VEC;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } POINTER;
            } X_IN_VEC;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } POINTER;
            } U0_VEC;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } POINTER;
            } U_OUT_VEC;
        } controller;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                struct {
                    logic [1:0] value;
                } MODE;
                struct {
                    logic [1:0] value;
                } CLK_DIV;
            } CONF;
            struct {
                struct {
                    logic [31:0] value;
                } DATA;
            } COUNT_TOP;
            struct {
                struct {
                    logic [31:0] value;
                } DATA;
            } COUNT_COMPARE;
        } pwm_ch[4];
        struct {
            struct {
                struct {
                    logic value;
                } RUN_CALC;
                struct {
                    logic value;
                } UPDATE_CONTROLLER;
                struct {
                    logic value;
                } UPDATE_CONTROLLER_REFERENCE;
                struct {
                    logic value;
                } UPDATE_CONTROLLER_STATE;
            } CMD;
            struct {
                struct {
                    logic [31:0] value;
                } POINTER;
            } K_MATRIX;
            struct {
                struct {
                    logic [31:0] value;
                } POINTER;
            } X_REF_VEC;
            struct {
                struct {
                    logic [31:0] value;
                } POINTER;
            } X_IN_VEC;
            struct {
                struct {
                    logic [31:0] value;
                } POINTER;
            } U0_VEC;
            struct {
                struct {
                    logic [31:0] value;
                } POINTER;
            } U_OUT_VEC;
        } controller;
    } field_storage_t;
    field_storage_t field_storage;

    for(genvar i0=0; i0<4; i0++) begin
        // Field: drone_controller_reg.pwm_ch[].CONF.MODE
        always_comb begin
            automatic logic [1:0] next_c;
            automatic logic load_next_c;
            next_c = field_storage.pwm_ch[i0].CONF.MODE.value;
            load_next_c = '0;
            if(decoded_reg_strb.pwm_ch[i0].CONF && decoded_req_is_wr) begin // SW write
                next_c = (field_storage.pwm_ch[i0].CONF.MODE.value & ~decoded_wr_biten[1:0]) | (decoded_wr_data[1:0] & decoded_wr_biten[1:0]);
                load_next_c = '1;
            end
            field_combo.pwm_ch[i0].CONF.MODE.next = next_c;
            field_combo.pwm_ch[i0].CONF.MODE.load_next = load_next_c;
        end
        always_ff @(posedge clk) begin
            if(rst) begin
                field_storage.pwm_ch[i0].CONF.MODE.value <= 2'h0;
            end else begin
                if(field_combo.pwm_ch[i0].CONF.MODE.load_next) begin
                    field_storage.pwm_ch[i0].CONF.MODE.value <= field_combo.pwm_ch[i0].CONF.MODE.next;
                end
            end
        end
        assign hwif_out.pwm_ch[i0].CONF.MODE.value = field_storage.pwm_ch[i0].CONF.MODE.value;
        // Field: drone_controller_reg.pwm_ch[].CONF.CLK_DIV
        always_comb begin
            automatic logic [1:0] next_c;
            automatic logic load_next_c;
            next_c = field_storage.pwm_ch[i0].CONF.CLK_DIV.value;
            load_next_c = '0;
            if(decoded_reg_strb.pwm_ch[i0].CONF && decoded_req_is_wr) begin // SW write
                next_c = (field_storage.pwm_ch[i0].CONF.CLK_DIV.value & ~decoded_wr_biten[3:2]) | (decoded_wr_data[3:2] & decoded_wr_biten[3:2]);
                load_next_c = '1;
            end
            field_combo.pwm_ch[i0].CONF.CLK_DIV.next = next_c;
            field_combo.pwm_ch[i0].CONF.CLK_DIV.load_next = load_next_c;
        end
        always_ff @(posedge clk) begin
            if(rst) begin
                field_storage.pwm_ch[i0].CONF.CLK_DIV.value <= 2'h0;
            end else begin
                if(field_combo.pwm_ch[i0].CONF.CLK_DIV.load_next) begin
                    field_storage.pwm_ch[i0].CONF.CLK_DIV.value <= field_combo.pwm_ch[i0].CONF.CLK_DIV.next;
                end
            end
        end
        assign hwif_out.pwm_ch[i0].CONF.CLK_DIV.value = field_storage.pwm_ch[i0].CONF.CLK_DIV.value;
        // Field: drone_controller_reg.pwm_ch[].COUNT_TOP.DATA
        always_comb begin
            automatic logic [31:0] next_c;
            automatic logic load_next_c;
            next_c = field_storage.pwm_ch[i0].COUNT_TOP.DATA.value;
            load_next_c = '0;
            if(decoded_reg_strb.pwm_ch[i0].COUNT_TOP && decoded_req_is_wr) begin // SW write
                next_c = (field_storage.pwm_ch[i0].COUNT_TOP.DATA.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
                load_next_c = '1;
            end
            field_combo.pwm_ch[i0].COUNT_TOP.DATA.next = next_c;
            field_combo.pwm_ch[i0].COUNT_TOP.DATA.load_next = load_next_c;
        end
        always_ff @(posedge clk) begin
            if(rst) begin
                field_storage.pwm_ch[i0].COUNT_TOP.DATA.value <= 32'h0;
            end else begin
                if(field_combo.pwm_ch[i0].COUNT_TOP.DATA.load_next) begin
                    field_storage.pwm_ch[i0].COUNT_TOP.DATA.value <= field_combo.pwm_ch[i0].COUNT_TOP.DATA.next;
                end
            end
        end
        assign hwif_out.pwm_ch[i0].COUNT_TOP.DATA.value = field_storage.pwm_ch[i0].COUNT_TOP.DATA.value;
        // Field: drone_controller_reg.pwm_ch[].COUNT_COMPARE.DATA
        always_comb begin
            automatic logic [31:0] next_c;
            automatic logic load_next_c;
            next_c = field_storage.pwm_ch[i0].COUNT_COMPARE.DATA.value;
            load_next_c = '0;
            if(decoded_reg_strb.pwm_ch[i0].COUNT_COMPARE && decoded_req_is_wr) begin // SW write
                next_c = (field_storage.pwm_ch[i0].COUNT_COMPARE.DATA.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
                load_next_c = '1;
            end
            field_combo.pwm_ch[i0].COUNT_COMPARE.DATA.next = next_c;
            field_combo.pwm_ch[i0].COUNT_COMPARE.DATA.load_next = load_next_c;
        end
        always_ff @(posedge clk) begin
            if(rst) begin
                field_storage.pwm_ch[i0].COUNT_COMPARE.DATA.value <= 32'h0;
            end else begin
                if(field_combo.pwm_ch[i0].COUNT_COMPARE.DATA.load_next) begin
                    field_storage.pwm_ch[i0].COUNT_COMPARE.DATA.value <= field_combo.pwm_ch[i0].COUNT_COMPARE.DATA.next;
                end
            end
        end
        assign hwif_out.pwm_ch[i0].COUNT_COMPARE.DATA.value = field_storage.pwm_ch[i0].COUNT_COMPARE.DATA.value;
    end
    // Field: drone_controller_reg.controller.CMD.RUN_CALC
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.controller.CMD.RUN_CALC.value;
        load_next_c = '0;
        if(decoded_reg_strb.controller.CMD && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.controller.CMD.RUN_CALC.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end else begin // singlepulse clears back to 0
            next_c = '0;
            load_next_c = '1;
        end
        field_combo.controller.CMD.RUN_CALC.next = next_c;
        field_combo.controller.CMD.RUN_CALC.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.controller.CMD.RUN_CALC.value <= 1'h0;
        end else begin
            if(field_combo.controller.CMD.RUN_CALC.load_next) begin
                field_storage.controller.CMD.RUN_CALC.value <= field_combo.controller.CMD.RUN_CALC.next;
            end
        end
    end
    assign hwif_out.controller.CMD.RUN_CALC.value = field_storage.controller.CMD.RUN_CALC.value;
    // Field: drone_controller_reg.controller.CMD.UPDATE_CONTROLLER
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.controller.CMD.UPDATE_CONTROLLER.value;
        load_next_c = '0;
        if(decoded_reg_strb.controller.CMD && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.controller.CMD.UPDATE_CONTROLLER.value & ~decoded_wr_biten[1:1]) | (decoded_wr_data[1:1] & decoded_wr_biten[1:1]);
            load_next_c = '1;
        end else begin // singlepulse clears back to 0
            next_c = '0;
            load_next_c = '1;
        end
        field_combo.controller.CMD.UPDATE_CONTROLLER.next = next_c;
        field_combo.controller.CMD.UPDATE_CONTROLLER.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.controller.CMD.UPDATE_CONTROLLER.value <= 1'h0;
        end else begin
            if(field_combo.controller.CMD.UPDATE_CONTROLLER.load_next) begin
                field_storage.controller.CMD.UPDATE_CONTROLLER.value <= field_combo.controller.CMD.UPDATE_CONTROLLER.next;
            end
        end
    end
    assign hwif_out.controller.CMD.UPDATE_CONTROLLER.value = field_storage.controller.CMD.UPDATE_CONTROLLER.value;
    // Field: drone_controller_reg.controller.CMD.UPDATE_CONTROLLER_REFERENCE
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.controller.CMD.UPDATE_CONTROLLER_REFERENCE.value;
        load_next_c = '0;
        if(decoded_reg_strb.controller.CMD && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.controller.CMD.UPDATE_CONTROLLER_REFERENCE.value & ~decoded_wr_biten[2:2]) | (decoded_wr_data[2:2] & decoded_wr_biten[2:2]);
            load_next_c = '1;
        end else begin // singlepulse clears back to 0
            next_c = '0;
            load_next_c = '1;
        end
        field_combo.controller.CMD.UPDATE_CONTROLLER_REFERENCE.next = next_c;
        field_combo.controller.CMD.UPDATE_CONTROLLER_REFERENCE.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.controller.CMD.UPDATE_CONTROLLER_REFERENCE.value <= 1'h0;
        end else begin
            if(field_combo.controller.CMD.UPDATE_CONTROLLER_REFERENCE.load_next) begin
                field_storage.controller.CMD.UPDATE_CONTROLLER_REFERENCE.value <= field_combo.controller.CMD.UPDATE_CONTROLLER_REFERENCE.next;
            end
        end
    end
    assign hwif_out.controller.CMD.UPDATE_CONTROLLER_REFERENCE.value = field_storage.controller.CMD.UPDATE_CONTROLLER_REFERENCE.value;
    // Field: drone_controller_reg.controller.CMD.UPDATE_CONTROLLER_STATE
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.controller.CMD.UPDATE_CONTROLLER_STATE.value;
        load_next_c = '0;
        if(decoded_reg_strb.controller.CMD && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.controller.CMD.UPDATE_CONTROLLER_STATE.value & ~decoded_wr_biten[3:3]) | (decoded_wr_data[3:3] & decoded_wr_biten[3:3]);
            load_next_c = '1;
        end else begin // singlepulse clears back to 0
            next_c = '0;
            load_next_c = '1;
        end
        field_combo.controller.CMD.UPDATE_CONTROLLER_STATE.next = next_c;
        field_combo.controller.CMD.UPDATE_CONTROLLER_STATE.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.controller.CMD.UPDATE_CONTROLLER_STATE.value <= 1'h0;
        end else begin
            if(field_combo.controller.CMD.UPDATE_CONTROLLER_STATE.load_next) begin
                field_storage.controller.CMD.UPDATE_CONTROLLER_STATE.value <= field_combo.controller.CMD.UPDATE_CONTROLLER_STATE.next;
            end
        end
    end
    assign hwif_out.controller.CMD.UPDATE_CONTROLLER_STATE.value = field_storage.controller.CMD.UPDATE_CONTROLLER_STATE.value;
    // Field: drone_controller_reg.controller.K_MATRIX.POINTER
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.controller.K_MATRIX.POINTER.value;
        load_next_c = '0;
        if(decoded_reg_strb.controller.K_MATRIX && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.controller.K_MATRIX.POINTER.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.controller.K_MATRIX.POINTER.next = next_c;
        field_combo.controller.K_MATRIX.POINTER.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.controller.K_MATRIX.POINTER.value <= 32'h0;
        end else begin
            if(field_combo.controller.K_MATRIX.POINTER.load_next) begin
                field_storage.controller.K_MATRIX.POINTER.value <= field_combo.controller.K_MATRIX.POINTER.next;
            end
        end
    end
    assign hwif_out.controller.K_MATRIX.POINTER.value = field_storage.controller.K_MATRIX.POINTER.value;
    // Field: drone_controller_reg.controller.X_REF_VEC.POINTER
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.controller.X_REF_VEC.POINTER.value;
        load_next_c = '0;
        if(decoded_reg_strb.controller.X_REF_VEC && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.controller.X_REF_VEC.POINTER.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.controller.X_REF_VEC.POINTER.next = next_c;
        field_combo.controller.X_REF_VEC.POINTER.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.controller.X_REF_VEC.POINTER.value <= 32'h0;
        end else begin
            if(field_combo.controller.X_REF_VEC.POINTER.load_next) begin
                field_storage.controller.X_REF_VEC.POINTER.value <= field_combo.controller.X_REF_VEC.POINTER.next;
            end
        end
    end
    assign hwif_out.controller.X_REF_VEC.POINTER.value = field_storage.controller.X_REF_VEC.POINTER.value;
    // Field: drone_controller_reg.controller.X_IN_VEC.POINTER
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.controller.X_IN_VEC.POINTER.value;
        load_next_c = '0;
        if(decoded_reg_strb.controller.X_IN_VEC && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.controller.X_IN_VEC.POINTER.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.controller.X_IN_VEC.POINTER.next = next_c;
        field_combo.controller.X_IN_VEC.POINTER.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.controller.X_IN_VEC.POINTER.value <= 32'h0;
        end else begin
            if(field_combo.controller.X_IN_VEC.POINTER.load_next) begin
                field_storage.controller.X_IN_VEC.POINTER.value <= field_combo.controller.X_IN_VEC.POINTER.next;
            end
        end
    end
    assign hwif_out.controller.X_IN_VEC.POINTER.value = field_storage.controller.X_IN_VEC.POINTER.value;
    // Field: drone_controller_reg.controller.U0_VEC.POINTER
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.controller.U0_VEC.POINTER.value;
        load_next_c = '0;
        if(decoded_reg_strb.controller.U0_VEC && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.controller.U0_VEC.POINTER.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.controller.U0_VEC.POINTER.next = next_c;
        field_combo.controller.U0_VEC.POINTER.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.controller.U0_VEC.POINTER.value <= 32'h0;
        end else begin
            if(field_combo.controller.U0_VEC.POINTER.load_next) begin
                field_storage.controller.U0_VEC.POINTER.value <= field_combo.controller.U0_VEC.POINTER.next;
            end
        end
    end
    assign hwif_out.controller.U0_VEC.POINTER.value = field_storage.controller.U0_VEC.POINTER.value;
    // Field: drone_controller_reg.controller.U_OUT_VEC.POINTER
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.controller.U_OUT_VEC.POINTER.value;
        load_next_c = '0;
        if(decoded_reg_strb.controller.U_OUT_VEC && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.controller.U_OUT_VEC.POINTER.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.controller.U_OUT_VEC.POINTER.next = next_c;
        field_combo.controller.U_OUT_VEC.POINTER.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.controller.U_OUT_VEC.POINTER.value <= 32'h0;
        end else begin
            if(field_combo.controller.U_OUT_VEC.POINTER.load_next) begin
                field_storage.controller.U_OUT_VEC.POINTER.value <= field_combo.controller.U_OUT_VEC.POINTER.next;
            end
        end
    end
    assign hwif_out.controller.U_OUT_VEC.POINTER.value = field_storage.controller.U_OUT_VEC.POINTER.value;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic [6:0] rd_mux_addr;
    assign rd_mux_addr = decoded_addr;

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_data_var = '0;
        for(int i0=0; i0<4; i0++) begin
            if(rd_mux_addr == 7'h0 + (7)'(i0) * 7'hc) begin
                readback_data_var[1:0] = field_storage.pwm_ch[i0].CONF.MODE.value;
                readback_data_var[3:2] = field_storage.pwm_ch[i0].CONF.CLK_DIV.value;
            end
            if(rd_mux_addr == 7'h4 + (7)'(i0) * 7'hc) begin
                readback_data_var[31:0] = field_storage.pwm_ch[i0].COUNT_TOP.DATA.value;
            end
            if(rd_mux_addr == 7'h8 + (7)'(i0) * 7'hc) begin
                readback_data_var[31:0] = field_storage.pwm_ch[i0].COUNT_COMPARE.DATA.value;
            end
        end
        readback_data = readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
