// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package drone_controller_reg_pkg;

    localparam DRONE_CONTROLLER_REG_DATA_WIDTH = 32;
    localparam DRONE_CONTROLLER_REG_MIN_ADDR_WIDTH = 7;
    localparam DRONE_CONTROLLER_REG_SIZE = 'h58;

    typedef struct {
        logic [1:0] value;
    } pwm_channel_t__CONF__MODE__out_t;

    typedef struct {
        logic [1:0] value;
    } pwm_channel_t__CONF__CLK_DIV__out_t;

    typedef struct {
        pwm_channel_t__CONF__MODE__out_t MODE;
        pwm_channel_t__CONF__CLK_DIV__out_t CLK_DIV;
    } pwm_channel_t__CONF__out_t;

    typedef struct {
        logic [31:0] value;
    } pwm_channel_t__COUNT_TOP__DATA__out_t;

    typedef struct {
        pwm_channel_t__COUNT_TOP__DATA__out_t DATA;
    } pwm_channel_t__COUNT_TOP__out_t;

    typedef struct {
        logic [31:0] value;
    } pwm_channel_t__COUNT_COMPARE__DATA__out_t;

    typedef struct {
        pwm_channel_t__COUNT_COMPARE__DATA__out_t DATA;
    } pwm_channel_t__COUNT_COMPARE__out_t;

    typedef struct {
        pwm_channel_t__CONF__out_t CONF;
        pwm_channel_t__COUNT_TOP__out_t COUNT_TOP;
        pwm_channel_t__COUNT_COMPARE__out_t COUNT_COMPARE;
    } pwm_channel_t__out_t;

    typedef struct {
        logic value;
    } controller_t__CMD__RUN_CALC__out_t;

    typedef struct {
        controller_t__CMD__RUN_CALC__out_t RUN_CALC;
    } controller_t__CMD__out_t;

    typedef struct {
        logic [31:0] value;
    } controller_t__K_MATRIX__POINTER__out_t;

    typedef struct {
        controller_t__K_MATRIX__POINTER__out_t POINTER;
    } controller_t__K_MATRIX__out_t;

    typedef struct {
        logic [31:0] value;
    } controller_t__X_REF_VEC__POINTER__out_t;

    typedef struct {
        controller_t__X_REF_VEC__POINTER__out_t POINTER;
    } controller_t__X_REF_VEC__out_t;

    typedef struct {
        logic [31:0] value;
    } controller_t__X_IN_VEC__POINTER__out_t;

    typedef struct {
        controller_t__X_IN_VEC__POINTER__out_t POINTER;
    } controller_t__X_IN_VEC__out_t;

    typedef struct {
        logic [31:0] value;
    } controller_t__U0_VEC__POINTER__out_t;

    typedef struct {
        controller_t__U0_VEC__POINTER__out_t POINTER;
    } controller_t__U0_VEC__out_t;

    typedef struct {
        logic [31:0] value;
    } controller_t__U_OUT_VEC__POINTER__out_t;

    typedef struct {
        controller_t__U_OUT_VEC__POINTER__out_t POINTER;
    } controller_t__U_OUT_VEC__out_t;

    typedef struct {
        controller_t__CMD__out_t CMD;
        controller_t__K_MATRIX__out_t K_MATRIX;
        controller_t__X_REF_VEC__out_t X_REF_VEC;
        controller_t__X_IN_VEC__out_t X_IN_VEC;
        controller_t__U0_VEC__out_t U0_VEC;
        controller_t__U_OUT_VEC__out_t U_OUT_VEC;
    } controller_t__out_t;

    typedef struct {
        pwm_channel_t__out_t pwm_ch[4];
        controller_t__out_t controller;
    } drone_controller_reg__out_t;

    typedef enum logic [1:0] {
        pwm_mode_e__PWM_MODE_DISABLED = 'h0,
        pwm_mode_e__PWM_MODE_EDGE_ALIGNED = 'h1,
        pwm_mode_e__PWM_MODE_CENTER_ALIGNED = 'h2,
        pwm_mode_e__PWM_MODE_RESERVED = 'h3
    } pwm_mode_e_e;

    typedef enum logic [1:0] {
        pwm_clk_div_e__CLK_DIV_1 = 'h0,
        pwm_clk_div_e__CLK_DIV_2 = 'h1,
        pwm_clk_div_e__CLK_DIV_4 = 'h2,
        pwm_clk_div_e__CLK_DIV_8 = 'h3
    } pwm_clk_div_e_e;
endpackage
